baseURL = ""
locale = "zh-CN"
title = "Xeu's world"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
summaryLength = 100
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "CommentPages"]

[outputFormats.CommentPages]
mediaType = "application/json"
baseName = "comment-pages"
isPlainText = true
notAlternative = true

[pagination]
pagerSize = 12
