name = "Xeu"
description = "Xeu's mini world"
mainSections = ["post"]
rssFullContent = true

[author]
name = "Xeu"
homepage = "https://github.com/OXeu"

[footer]
since = 2020

[article]
license = "CC BY-NC-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/"

[comments]
enabled = true
